### ISSUE TITLE
Label with icon

### ISSUE THREAD

**Issue by Green-loutre** [lawnstarter/react-native-picker-select#158]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

It would be amazing to be able to pass an Icon (and/or Image) for the label to be displayed with a string or to display the Icon(and/or Image) only (I really need both use cases)
Thank you!

**Comment by lfkwtz** [comment]
- If you want this to appear when the picker is actually open, that can't be done as the native picker elements just accept a string
- If you want this to appear in the TextInput itself **after** something has been selected, that would be challenging because the TextInput also expects strings. What you could possibly do is utilize the Icon prop (or just create an absolute positioned element outside of this component) that dynamically updates based on the selected item.
- The cleanest solution would be to either use the headless mode and recreate the input that you need ... or use emojis.

**Comment by Green-loutre** [comment]
Thank you a lot for your answer :)
