### ISSUE TITLE
Chevron disappears on Android with useNativeAndroidPickerStyle set to false and padding

### ISSUE THREAD

**Issue by jdhorner** [lawnstarter/react-native-picker-select#203]
**Describe the bug**<br />
When setting `useNativeAndroidPickerStyle={false}` 
and adding `inputAndroid: { paddingVertical: 8 }`, 
the chevron disappears. Removing the padding reintroduces the chevron.

**To Reproduce**<br />

1. Set up a simple RNPicker instance
2. Set useNativeAndroidPickerStyle to false
3. Add vertical padding to the component
4. See how the chevron disappears

**Expected behavior**<br />
The dropdown chevron should always be visible if only changing the vertical padding of the input.

**Screenshots**<br />
![2019-07-29 17_28_07-Snack](https://user-images.githubusercontent.com/2692640/62084345-1f4b2d80-b227-11e9-9fff-16f0a2a4aab2.png)

**Smartphone (please complete the following information):**<br />
-   Device: [Google Pixel 3 Emulator]
-   OS: [Android 9 Pie]
-   react-native-picker-select version: [6.3.0]
-   react-native version: [Expo v33]
-   react version: [Expo v33]

**Reproduction and/or code sample**<br />
You can view the snack here: https://snack.expo.io/SJbzLk6MS

**Comment by jdhorner** [comment]
Obviously, choose "Android" in the Snack preview pane.

**Comment by lfkwtz** [comment]
The issue here is that the TextInput you're styling pushes the native input enough at a certain padding limit that it hides the arrow. The headless mode on Android is definitely a workaround to the issue of not being able to trigger the picker programmatically - so any changes made to the structure / styling which enable it's current functionality would have to be made carefully as to not break it. I'm open to prs and/or suggestions on how this can be achieved and am happy to leave this open for a bit (or maybe move it to the feature request board) - but I think the better solution for you would be to utilize a custom icon. The non-native picker is intended for those that want to style it more heavily than the native picker will allow - which it sounds like is your usecase.

**Comment by jdhorner** [comment]
Well, really, the only reason I went with `useNativeAndroidPickerStyle={false}` was to deal with padding. But if there's a way to make the native one remove these circled spacing areas, that would be amazing! 

![Screenshot_1564500037](https://user-images.githubusercontent.com/2692640/62142462-66373280-b2bc-11e9-97b3-a15702355472.png)

If _not_, I'll do as you suggest, and custom style it with a separate icon. And do as you wish with this issue; as-described, it apparently isn't a bug, but simply a limitation.

**Comment by lfkwtz** [comment]
if that's all you're wanting to accomplish, what about wrapping the component (with useNativeAndroidPickerStyle set to true) in a view with negative margin on the sides?

https://snack.expo.io/HJVE3JRMr

**Comment by jdhorner** [comment]
> if that's all you're wanting to accomplish, what about wrapping the component (with useNativeAndroidPickerStyle set to true) in a view with negative margin on the sides?

So I'll be honest... I had no idea negative margins were even a "thing". It worked like a charm. Thank you.

**Comment by lfkwtz** [comment]
will live on the feature request board. if anyone has suggestions on how we can improve android headless - i'm open to it.

**Comment by akkravikumar** [comment]
@jdhorner use this style below, it should work.
inputAndroid: {
    borderWidth: 1,
    borderColor: "red",    
    elevation: 2,
    color: "#000000"
}
