### ISSUE TITLE
Help Wanted – Android Picker Everywhere/Single Select

### ISSUE THREAD

**Issue by Jacob-o** [lawnstarter/react-native-picker-select#284]
Hello Mr.Lefkowitz. Hope all is well. I am a senior about to graduate university and I'm looking to use this library in a project for my capstone course. With how the library is built now, is there a way to use Android UI on IOS? What I want to solve is that I don't want users having to tap the done button after selecting their choice. I would prefer the Android UI of a pop up that closes upon selection. Is there anyway of doing that on IOS with this library? 

Thanks so much for your time!

**Comment by lfkwtz** [comment]
Not possible - it uses native UI components that are explicit to each platform.

You could use the onChange callback to auto close the iOS picker though - but that would be poor UX in my opinion - due to the way iOS displays options in a wheel vs presenting all at once on a sheet like Android.

Best of luck on your course.
