### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by brownieboy** [lawnstarter/react-native-picker-select#510]
**Is your feature request related to a problem? Please describe.**<br>
What the subject header says.

No updates to the project since the last release 3 years ago.   So is anybody still working on it?

**Comment by keithdmoore94** [comment]
@LawnStarterTeam First of all, this is a great library!  I have used in on a couple of projects.  Would you guys add some more maintainers so that this library can keep on living and be maintained?  I think the community at large would appreciate it.  I would like to be a maintainer as well.  Thanks!

**Comment by Jonnx** [comment]
The original maintainer has reached out and is resuming work on this package. Maintaining this is something that slipped through the cracks and we should have done better. 

Hopefully with @lfkwtz expressing interest in (and having been given access) to main the project he originally brought to life, this situation will improve.
